[versions]
assertJ = "3.27.6"
commonsLang3 = "3.20.0"
junitJupiter = "6.0.1"
openpdf = "3.0.0"

[libraries]
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertJ"}
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commonsLang3"}
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter"}
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junitJupiter" }
openpdf = { group = "com.github.librepdf", name = "openpdf", version.ref = "openpdf" }

[bundles]
junit-jupiter = ["assertj-core", "junit-jupiter-api", "junit-jupiter-engine", "junit-jupiter-params"]
